// Expose React and ReactDOM

import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { AlertProvider } from "./components/multiverse/Alert";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={" text-white-100 antialiased"}>
				<AlertProvider maxAlerts={7}>{children}</AlertProvider>
			</body>
		</html>
	);
}
